### ISSUE TITLE
"Too many element types registered", probably registering them multiple times?

### ISSUE THREAD

**Issue by ScoreUnder** [walt-grace/glsl-plugin-idea#6]
After a few hours of messing with GLSL files with this plugin installed, the following error will occur:

```
java.lang.Throwable: Too many element types registered. Out of (short) range. Most of element types (12794) were registered for 'Language: Glsl': FILE, FILE, FILE, ADD_EXPR, AND_EXPR, ARRAY_SPECIFIER, ASSIGNMENT_EXPR, ASSIGNMENT_OPERATOR, ATTRIBUTE, BLOCK_STRUCTURE, BLOCK_STRUCTURE_WRAPPER, CASE_LABEL, COMPOUND_STATEMENT, COMPOUND_STATEMENT_NO_NEW_SCOPE, CONDITION, CONDITIONAL_EXPR, CONSTANT_EXPR, DECLARATION, DECLARATION_IDENTIFIER_WRAPPER, ...
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.psi.tree.IElementType.<init>(IElementType.java:121)
	at com.intellij.psi.tree.IElementType.<init>(IElementType.java:99)
	at com.intellij.psi.tree.ILazyParseableElementType.<init>(ILazyParseableElementType.java:29)
	at com.intellij.psi.tree.IFileElementType.<init>(IFileElementType.java:30)
	at glsl.plugin.language.GlslParserDefinition.getFileNodeType(GlslLanguage.kt:69)
	at com.intellij.extapi.psi.PsiFileBase.<init>(PsiFileBase.java:29)
	at glsl.plugin.language.GlslFile.<init>(GlslFile.kt:14)
	at glsl.plugin.language.GlslParserDefinition.createFile(GlslLanguage.kt:104)
	at com.intellij.psi.AbstractFileViewProvider.createFile(AbstractFileViewProvider.java:144)
	at com.intellij.psi.AbstractFileViewProvider.createFile(AbstractFileViewProvider.java:128)
	at com.intellij.psi.AbstractFileViewProvider.createFile(AbstractFileViewProvider.java:117)
	at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:144)
	at com.intellij.psi.SingleRootFileViewProvider.getPsiInner(SingleRootFileViewProvider.java:100)
	at com.intellij.psi.AbstractFileViewProvider.getPsi(AbstractFileViewProvider.java:194)
	at com.intellij.psi.impl.BlockSupportImpl.getFileCopy(BlockSupportImpl.java:307)
	at com.intellij.psi.impl.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:289)
	at com.intellij.psi.impl.BlockSupportImpl.reparse(BlockSupportImpl.java:92)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:261)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:128)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitAsynchronously$0(DocumentCommitThread.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by walt-grace** [comment]
How can I reproduce the bug?

**Comment by ScoreUnder** [comment]
There doesn't seem to be any trigger in particular. Just using the IDE for a while, editing GLSL scripts with the plugin installed, seems to be enough. I don't really keep track of time very well but it's probably after a couple of hours of active use.

**Comment by benburrill** [comment]
I don't understand why this is closed.  Even if you are unwilling to edit a file for long enough to reproduce the error, the stack trace seems to be pretty clear in indicating that when [you create new instances](https://github.com/walt-grace/glsl-plugin-idea/blob/137355b8ebeac3934fe92e2ae3c9d06b62f035b0/src/main/kotlin/glsl/plugin/language/GlslLanguage.kt#L69) of `IFileElementType` in `getFileNodeType` they are being stored permanently, until eventually too many get registered.

I don't have any experience with Intellij plugin development, but I see [here](https://github.com/JetBrains/intellij-community/blob/c047a5caf941e5522efcf339eef7b660afa2e300/platform/core-api/src/com/intellij/psi/tree/IFileElementType.java#L26) that there's a constructor that takes a parameter `register` to disable registering of the element type.  That might be an option to fix this bug if there really is a valid reason for creating new instances all the time.  Alternatively, I see in [this example](https://plugins.jetbrains.com/docs/intellij/lexer-and-parser-definition.html#define-a-parser) FILE element type is defined as a static variable returned by getFileNodeType instead of being constructed each time.  That seems like the better option if you can do it.

As for why the file node types seem to be created for every edit in the first place, my guess is that it is due to [this](https://github.com/walt-grace/glsl-plugin-idea/blob/137355b8ebeac3934fe92e2ae3c9d06b62f035b0/src/main/kotlin/glsl/plugin/psi/GlslIdentifier.kt#L84), which seems rather odd.  Is there really no better way to change the name of an identifier?
